### ISSUE TITLE
Trouble with development mode

### ISSUE THREAD

**Issue by rsaccon** [Raincal/parcel-reason-react-app#1]
I cloned the repo, followed the instructions to build and start and worked as expected, could access the app on localhost:1234

Then I did some changes, saved  and expected after browser refresh to see these changes having been applied, unfortunately this was not the case. Only way to get the app updated was to kill the dev server and restart it with `yarn start`. I guess this is not how it is supposed to be. (in a non-parcel reasons project of mine, I just run `yarn start` which has file-watcher enabled `bsb -make-world -w` and all worked as expected)

I did try to make Visual Studio Code to run bsb after each file-save, but that did not work (a "save" caused **all** *.bs.js to get deleted), but I guess this is a different problem, specific to my editor.

I tried to do run manually a `yarn build` after file save, but that resulted in total corrupt output, after browser refresh I got a the browser console:
```
Uncaught SyntaxError: Unexpected token <
```
I also tried to run separately a `bsb -make-world -w` script, but that did also not work.

So my only option: Restarting the dev server, but that takes about 2 seconds at my setup!

So how is the development workflow supposed to be ?

**Comment by rsaccon** [comment]
SOLVED ! I had a different (older) global bs-platform. After updating that, all went as expected. Closing it

**Comment by Raincal** [comment]
Thanks for your feedback!
I have just updated the codes.
- add watch mode
- add HMR
